name: oracledb
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: container-registry.oracle.com/database/free:latest
      env:
        ORACLE_PWD: ${{ secrets.DBPS }}
      ports:
        - 1521:1521
      volumes:
        - oracle-data:/opt/oracle/oradata
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

